repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ --maxkb=1000 ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
        - id: black

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'cd mypy'
        language: system
        types: [python]